### ISSUE TITLE
Error with 9x9 board

### ISSUE THREAD

**Issue by debadeepta** [pasky/michi#12]
When using the command to start the system it errors out using 9x9 (-size 9) boards but works fine with 13x13 boards.

**Comment by traveller42** [comment]
The program is hardcoded for 13x13.

The size is set with the value, N, near the top of the program.

Is it throwing a traceback, or just indicating that the size is not supported?

**Comment by debadeepta** [comment]
Just indicating that the size is not supported. I changed the commandline to be be '-size 13x13' and then it ran through properly. No big deal just thought I would let you know.

**Comment by pasky** [comment]
Thanks for the report, but I believe this is docummented.
