### ISSUE TITLE
Error for gnugo

### ISSUE THREAD

**Issue by jianboyang** [pasky/michi#6]
Hi 

When I run the command "gogui-twogtp -black './michi.py gtp' -white 'gnugo --mode=gtp --chinese-rules --capture-all-dead' -size 9 -komi 7.5 -verbose -auto", I got the following error:

"Cannot run program "/home/XXX/Documents/CNN_GO/michi/michi-master/gnugo": error=13, Permission denied"

Any idea please? Thanks!

**Comment by ujh** [comment]
Just to make sure: Have you installed GnuGo?

**Comment by jianboyang** [comment]
Yes. When I type GnuGO, it shows:

GNU Go 3.8
Copyright 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007
2008 and 2009 by the Free Software Foundation, Inc.
See http://www.gnu.org/software/gnugo/ or contact
gnugo@gnu.org for information about GNU Go. GNU Go comes with NO WARRANTY to
the extent permitted by law. This program is free software; you can
redistribute it and/or modify it under the terms of the GNU General Public
License as published by the Free Software Foundation - version 3 or
(at your option) any later version. For more
information about these matters, see the files named COPYING.

Beginning ASCII mode game.
.......

**Comment by traveller42** [comment]
What happens if you try to get gnugo to play itself?

What operating system are you using?

What files are in the michi-master directory?

I'm not currently where I can try that command myself, but I will likely be able to try to reproduce that error on Sunday.

**Comment by jianboyang** [comment]
Thanks for response!

Can you tell me what the command in terminal is for getting gnugo play iteself in GoGUI please?

OS:
Ubuntu 14.04.1 LTS

Files/Folder under michi-master directory:
michi.py
patterns.prob
patterns.spat
README.md
gnugo-3.8.tar.gz
gogui-1.4.9.zip
gnugo/  (unzip gnugo-3.8.tar.gz and change the folder name to "gnugo")
gogui/   (unzip gogui-1.4.9.zip and change the folder name to "gogui")

I already installed GoGui and GNUgo following their readme files. Thus, in terminal:
when I type "gogui", the graphical interface of GoGui comes out.
when I type "gnugo", the following things show up in the terminal

---

GNU Go 3.8
Copyright 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007
2008 and 2009 by the Free Software Foundation, Inc.
See http://www.gnu.org/software/gnugo/ or contact
gnugo@gnu.org for information about GNU Go. GNU Go comes with NO WARRANTY to
the extent permitted by law. This program is free software; you can
redistribute it and/or modify it under the terms of the GNU General Public
License as published by the Free Software Foundation - version 3 or
(at your option) any later version. For more
information about these matters, see the files named COPYING.

Beginning ASCII mode game.

Board Size:   19
Handicap      0
Komi:         0.0
Move Number:  0
To Move:      black
Computer player: White

```
White (O) has captured 0 pieces
Black (X) has captured 0 pieces

A B C D E F G H J K L M N O P Q R S T
```

 19 . . . . . . . . . . . . . . . . . . . 19
 18 . . . . . . . . . . . . . . . . . . . 18
 17 . . . . . . . . . . . . . . . . . . . 17
 16 . . . + . . . . . + . . . . . + . . . 16
 15 . . . . . . . . . . . . . . . . . . . 15
 14 . . . . . . . . . . . . . . . . . . . 14
 13 . . . . . . . . . . . . . . . . . . . 13
 12 . . . . . . . . . . . . . . . . . . . 12
 11 . . . . . . . . . . . . . . . . . . . 11
 10 . . . + . . . . . + . . . . . + . . . 10
  9 . . . . . . . . . . . . . . . . . . .  9
  8 . . . . . . . . . . . . . . . . . . .  8
  7 . . . . . . . . . . . . . . . . . . .  7
  6 . . . . . . . . . . . . . . . . . . .  6
  5 . . . . . . . . . . . . . . . . . . .  5
  4 . . . + . . . . . + . . . . . + . . .  4
  3 . . . . . . . . . . . . . . . . . . .  3
  2 . . . . . . . . . . . . . . . . . . .  2
  1 . . . . . . . . . . . . . . . . . . .  1
    A B C D E F G H J K L M N O P Q R S T

black(1): 

---

But, when I type  "gogui-twogtp -black './michi.py gtp' -white 'gnugo --mode=gtp --chinese-rules --capture-all-dead' -size 9 -komi 7.5 -verbose -auto", the above mentioned error happens.

**Comment by pasky** [comment]
What if you try referring to the gnugo command by the full path in the twogtp command line?

**Comment by jianboyang** [comment]
Just tried "gogui-twogtp -black './michi.py gtp' -white '/home/XXX/Documents/CNN_GO/michi/michi-master/gnugo --mode=gtp --chinese-rules --capture-all-dead' -size 9 -komi 7.5 -verbose -auto"
and the same error happens.

FYI, the working directory in terminal is already "/home/XXX/Documents/CNN_GO/michi/michi-master"

**Comment by pasky** [comment]
But from your previous post, it seemed that
/home/XXX/Documents/CNN_GO/michi/michi-master/gnugo
is a directory, not the executable?

**Comment by traveller42** [comment]
To have an engine play against itself, you specific the same arguments for both White and Black.

I agree that it appears that you have specified the directory created by the untar.

What are the contents of the gnugo directory?

**Comment by jianboyang** [comment]
Thanks, pasky and traveller! The program can run now. GnuGo directory is /usr/local/bin/.
